services:
  - type: web
    name: z-ai2api
    env: python
    autoDeploy: true
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_TOKEN
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET_KEY
        sync: false
      - key: PORT
        value: 8080
      - key: LISTEN_PORT
        value: 8080